### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by Gcaufy** [li-xianfeng/wepy-plugin-autoprefixer#2]
非常感谢autoprefixer插件的实现。
最近群里也在问题autoprefixer的事情，然后我也写了一个，提交后发现npm已被注册了。
大多数人不知道这个插件的存在，不知道是否愿意PR到我的repo，然后npm给我提交一个权限呢？
https://github.com/wepyjs/wepy/issues/434

**Comment by li-xianfeng** [comment]
@Gcaufy 之前自己需要这个功能看官方没有就自己封装了下，刚刚发了PR,改了文档和package.json，代码都差不多一样就没做修改，npm给你加了权限。
